name: Deploy to Netlify

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  actions: write
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
    steps:
      - uses: fntsrlike/action-netlify-deploy@v2
        with: 
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_DEPLOY_TO_PROD: true
          build_command: npm run build
          
