name: Build and Deploy to Netlify
on:
  push:
    branches:
      - '!refs/pull/*'
  workflow_dispatch:
jobs:

  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Check commit for release conditions
        id: is-release-required
        uses: steviemul/commit-conditions@v1.0.0
        with:
          success-commit-message: '(deploy)'
          fail-commit-message: '(no deploy)'
          excludes: >
            .github/workflows/*.yml,
            README.md

      - name: Set outputs
        run: |   # Use a multi-line string
          if [[ ${{ steps.is-release-required.outputs }} == true ]]; then
            echo "deploying"
          fi

  build:
    needs: check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22.x]

    if: needs.check.outputs.result == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Check Release Required
        run: |
          ${{ steps.is-release-required.outputs.result }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1